import { wants } from '../model.js'

// Hermes Agent (NousResearch). Project scope only — Hermes keeps MCP, hooks,
// permissions, and slash commands in ~/.hermes/config.yaml (global), which this
// tool never writes. Rules are also skipped: generating .hermes.md would shadow
// the hand-authored AGENTS.md, which Hermes already reads natively
// (discovery order: .hermes.md → HERMES.md → AGENTS.md → CLAUDE.md).
//
// What Hermes DOES get at project scope: subagents, encoded as JSON specs plus
// a Python plugin that registers each one as a delegate_task command.

const slug = (name) => name.replace(/[^a-zA-Z0-9_-]/g, '_')

const PLUGIN_YAML = `name: meta-harness-subagents
version: "1.0.0"
description: Exposes meta-harness subagents as Hermes delegation commands.
`

const PLUGIN_INIT = `# generated by meta-harness — do not edit
import json
from pathlib import Path


def register(ctx):
    specs_dir = Path(__file__).resolve().parents[2] / "rulesync" / "subagents"
    if not specs_dir.is_dir():
        return
    for spec_path in sorted(specs_dir.glob("*.json")):
        spec = json.loads(spec_path.read_text())

        def make_handler(spec):
            def handler(args=""):
                context = spec["prompt"]
                if args:
                    context += "\\n\\nUser arguments:\\n" + args
                return ctx.dispatch_tool(
                    "delegate_task",
                    {"goal": spec["description"], "context": context, "toolsets": spec["toolsets"]},
                )

            return handler

        ctx.register_command(spec["hermes"]["command"], make_handler(spec), spec["description"])
`

export default {
  name: 'hermes',
  emit(model, ctx) {
    const out = []
    const agents = model.agents.filter((a) => wants(a, 'hermes'))
    if (!agents.length) {
      if (model.rules.length && model.rules.some((r) => r.targets.includes('hermes')))
        ctx.warnings.push('hermes: rules are not emitted — Hermes reads the hand-authored AGENTS.md natively')
      return out
    }

    for (const a of agents) {
      const s = slug(a.name)
      out.push({
        category: 'agents',
        path: `.hermes/rulesync/subagents/${s}.json`,
        content:
          JSON.stringify(
            {
              slug: s,
              name: a.name,
              description: a.shared.description ?? `Delegate work to the ${a.name} subagent.`,
              prompt: a.body,
              toolsets: a.perTarget.hermes?.toolsets ?? ['terminal', 'file', 'web'],
              hermes: { command: `subagent_${s}`, dispatch: 'delegate_task' },
            },
            null,
            2
          ) + '\n',
      })
    }
    out.push({ category: 'agents', path: '.hermes/plugins/meta-harness-subagents/plugin.yaml', content: PLUGIN_YAML })
    out.push({ category: 'agents', path: '.hermes/plugins/meta-harness-subagents/__init__.py', content: PLUGIN_INIT })
    return out
  },
}
