import path from 'node:path'
import matter from 'gray-matter'
import { flattenHookDefs, resolveEvents, resolveServers, wants } from '../model.js'

const EVENT_MAP = {
  SessionStart: 'session.created',
  PreToolUse: 'tool.execute.before',
  PostToolUse: 'tool.execute.after',
  Stop: 'session.idle',
  PermissionRequest: 'permission.asked',
}

// ${VAR} → {env:VAR} (opencode's env-ref syntax).
const envRefs = (x) => JSON.parse(JSON.stringify(x).replace(/\$\{(\w+)\}/g, '{env:$1}'))

// Canonical server map → opencode.json `mcp` + `tools` keys.
function toOpencode(servers) {
  const mcp = {}
  const tools = {}
  for (const [name, cfg] of Object.entries(servers)) {
    const remote = Boolean(cfg.url ?? cfg.httpUrl)
    const s = { type: remote ? 'remote' : 'local' }
    if (remote) s.url = cfg.url ?? cfg.httpUrl
    else s.command = [cfg.command, ...(cfg.args ?? [])].filter(Boolean)
    if (cfg.env && Object.keys(cfg.env).length) s.environment = cfg.env
    if (cfg.headers) s.headers = cfg.headers
    if (cfg.cwd) s.cwd = cfg.cwd
    if (cfg.timeout) s.timeout = cfg.timeout
    if (cfg.oauth) s.oauth = cfg.oauth
    s.enabled = cfg.disabled !== true
    mcp[name] = s
    for (const t of cfg.enabledTools ?? []) tools[`${name}_${t}`] = true
    for (const t of cfg.disabledTools ?? []) tools[`${name}_${t}`] = false
  }
  return { mcp: envRefs(mcp), tools }
}

const esc = {
  regex: (s) => s.replace(/[\\"]/g, '\\$&'),
  cmd: (s) => s.replace(/[\\`]/g, '\\$&').replace(/\$\{/g, '\\${'),
}

// OpenCode has no native hooks config — generate a plugin module instead.
function hooksPlugin(events, warnings) {
  const toolHandlers = []
  const eventBranches = []
  for (const [ev, entries] of Object.entries(events)) {
    const native = EVENT_MAP[ev]
    const defs = flattenHookDefs(entries).filter((d) => d.type === 'command' && d.command)
    if (!defs.length) continue
    const body = defs
      .map((d) => {
        const run = `await $\`${esc.cmd(d.command)}\`;`
        if (!d.matcher || d.matcher === '*') return `      ${run}`
        try {
          new RegExp(d.matcher)
        } catch {
          warnings.push(`hooks: invalid matcher regex "${d.matcher}" for opencode — skipped`)
          return null
        }
        return `      if (new RegExp("${esc.regex(d.matcher)}").test(input.tool)) { ${run} }`
      })
      .filter(Boolean)
      .join('\n')
    if (native.startsWith('tool.execute.'))
      toolHandlers.push(`    "${native}": async (input) => {\n${body}\n    },`)
    else
      eventBranches.push(`      if (event.type === "${native}") {\n  ${body}\n      }`)
  }
  const eventHandler = eventBranches.length
    ? `    event: async ({ event }) => {\n${eventBranches.join('\n')}\n    },`
    : ''
  return [
    '// generated by meta-harness — do not edit',
    'export const MetaHarnessHooksPlugin = async ({ $ }) => {',
    '  return {',
    eventHandler,
    ...toolHandlers,
    '  };',
    '};',
    '',
  ]
    .filter(Boolean)
    .join('\n')
}

export default {
  name: 'opencode',
  emit(model, ctx) {
    const out = []

    // rules reach OpenCode via AGENTS.md, which it reads natively (agentsmd.js)

    for (const c of model.commands.filter((c) => wants(c, 'opencode'))) {
      const fm = { ...(c.fm.description ? { description: c.fm.description } : {}), ...(c.fm.opencode ?? {}) }
      out.push({
        category: 'commands',
        path: path.join('.opencode/commands', `${c.name}.md`),
        content: Object.keys(fm).length ? matter.stringify(`\n${c.body}\n`, fm) : c.body + '\n',
      })
    }

    for (const a of model.agents.filter((a) => wants(a, 'opencode'))) {
      const fm = { description: a.shared.description, mode: 'subagent', ...(a.perTarget.opencode ?? {}) }
      out.push({
        category: 'agents',
        path: path.join('.opencode/agents', `${a.name}.md`),
        content: matter.stringify(`\n${a.body}\n`, fm),
      })
    }

    const servers = model.mcp ? resolveServers(model.mcp, 'opencode') : {}
    if (Object.keys(servers).length) {
      const { mcp, tools } = toOpencode(servers)
      const data = { mcp }
      if (Object.keys(tools).length) data.tools = tools
      out.push({ category: 'connections', sharedFile: 'opencode.json', format: 'json', data })
    }

    if (model.hooks) {
      const events = resolveEvents(model.hooks, 'opencode', Object.keys(EVENT_MAP), ctx.warnings)
      if (Object.keys(events).length)
        out.push({
          category: 'hooks',
          path: '.opencode/plugins/meta-harness-hooks.js',
          content: hooksPlugin(events, ctx.warnings),
        })
    }

    return out
  },
}
