// AGENTS.md is the single prose-rules channel: every supported runtime reads
// it natively except Claude Code, which gets a generated CLAUDE.md stub that
// imports it (@AGENTS.md). Rather than generate the whole file — it is an
// identity file people write themselves — meta-harness owns one
// marker-delimited block and leaves everything around it untouched. Same
// ownership model as the shared JSON/TOML files: own a region, preserve the
// rest, hash only what we own.

import path from 'node:path'
import { wants } from './model.js'
import { readIf } from './util.js'

export const START = '<!-- meta-harness:start -->'
export const END = '<!-- meta-harness:end -->'

export const blockBody = (rules) =>
  [
    START,
    '<!-- Generated from your meta-harness rules. Edit them there, not here;',
    '     anything outside this block is yours and is never touched. -->',
    '',
    ...rules.map((r) => r.body.trim()).flatMap((b) => [b, '']),
    END,
  ].join('\n')

// Splice the block into whatever the user already has.
export function spliceBlock(existing, block) {
  if (existing === null) return `${block}\n`
  const s = existing.indexOf(START)
  const e = existing.indexOf(END)
  if (s !== -1 && e !== -1 && e > s) return existing.slice(0, s) + block + existing.slice(e + END.length)
  // No block yet — append, keeping their prose first since it's the file's point.
  return `${existing.trimEnd()}\n\n${block}\n`
}

export const extractBlock = (raw) => {
  const s = raw.indexOf(START)
  const e = raw.indexOf(END)
  return s !== -1 && e !== -1 && e > s ? raw.slice(s, e + END.length) : null
}

const CLAUDE_STUB = [
  START,
  '<!-- Generated by meta-harness: Claude Code reads rules through this import. -->',
  '',
  '@AGENTS.md',
  '',
  END,
].join('\n')

// One output, regardless of how many targets are enabled — every runtime
// reads the same AGENTS.md, so emitting per target would collide on the file.
export function emitAgentsMd(model, targetNames, ctx) {
  const rules = model.rules.filter((r) => targetNames.some((t) => wants(r, t)))
  if (!rules.length) return []
  // AGENTS.md is one shared file: a rule's `targets` can only decide whether
  // it is included at all (any enabled target wants it), not who reads it.
  for (const r of rules.filter((r) => !r.targets.includes('*')))
    ctx.warnings.push(
      `AGENTS.md: rule "${r.name}" narrows targets, but AGENTS.md is shared — every enabled runtime will read it`
    )
  // `root: true` leads the file. Identity ("you are the orchestrator, this is
  // the source of truth") only does its job if it is read before the rules it
  // frames, and filename ordering is too implicit to rely on for that.
  const ordered = [...rules.filter((r) => r.fm.root), ...rules.filter((r) => !r.fm.root)]
  const out = [{ category: 'rules', path: 'AGENTS.md', markerFile: true, block: blockBody(ordered) }]
  if (targetNames.includes('claude')) {
    // Claude Code does not read AGENTS.md; the @AGENTS.md import in CLAUDE.md
    // is its only path to the rules. A stub file, never a symlink — Claude
    // refuses to write through a symlinked CLAUDE.md. If the user already
    // imports AGENTS.md themselves, their file is complete as-is.
    const existing = readIf(path.join(ctx.root, 'CLAUDE.md'))
    // Line-anchored: `@AGENTS.md` only imports when it stands on its own line.
    if (existing === null || existing.includes(START) || !/^@AGENTS\.md\s*$/m.test(existing))
      out.push({ category: 'rules', path: 'CLAUDE.md', markerFile: true, block: CLAUDE_STUB })
  }
  return out
}
