// AGENTS.md is the single prose-rules channel: every supported runtime reads
// it natively except Claude Code, which gets a generated CLAUDE.md stub that
// imports it (@AGENTS.md). Both are whole-file outputs, compiled entirely
// from rules/ — same ownership contract as every other generated file. A
// user's own prose belongs in a rules file (e.g. rules/project.md with
// `root: true`), not hand-edited into the output.

import { wants } from './model.js'

// Legacy markers from the pre-0.18 co-owned block. Kept only so generate can
// refuse before clobbering prose a user wrote outside the old block.
export const START = '<!-- meta-harness:start -->'
export const END = '<!-- meta-harness:end -->'

export const legacyProse = (raw) => {
  const s = raw.indexOf(START)
  const e = raw.indexOf(END)
  if (s === -1 || e === -1 || e <= s) return null
  return (raw.slice(0, s) + raw.slice(e + END.length)).trim()
}

const HEADER = '<!-- Generated by meta-harness from your rules/ sources. Edit those, not this file. -->'

const CLAUDE_STUB = [
  '<!-- Generated by meta-harness: Claude Code reads the rules through this import. -->',
  '',
  '@AGENTS.md',
  '',
].join('\n')

// One output, regardless of how many targets are enabled — every runtime
// reads the same AGENTS.md, so emitting per target would collide on the file.
export function emitAgentsMd(model, targetNames, ctx) {
  const rules = model.rules.filter((r) => targetNames.some((t) => wants(r, t)))
  if (!rules.length) return []
  // AGENTS.md is one shared file: a rule's `targets` can only decide whether
  // it is included at all (any enabled target wants it), not who reads it.
  for (const r of rules.filter((r) => !r.targets.includes('*')))
    ctx.warnings.push(
      `AGENTS.md: rule "${r.name}" narrows targets, but AGENTS.md is shared — every enabled runtime will read it`
    )
  // `root: true` leads the file. Identity ("you are the orchestrator, this is
  // the source of truth") only does its job if it is read before the rules it
  // frames, and filename ordering is too implicit to rely on for that.
  const ordered = [...rules.filter((r) => r.fm.root), ...rules.filter((r) => !r.fm.root)]
  const content = [HEADER, '', ...ordered.map((r) => r.body.trim()).flatMap((b) => [b, ''])].join('\n')
  const out = [{ category: 'rules', path: 'AGENTS.md', content }]
  // Claude Code does not read AGENTS.md; the @AGENTS.md import in CLAUDE.md
  // is its only path to the rules. A stub file, never a symlink — Claude
  // refuses to write through a symlinked CLAUDE.md.
  if (targetNames.includes('claude')) out.push({ category: 'rules', path: 'CLAUDE.md', content: CLAUDE_STUB })
  return out
}
