// Unified permissions. One declaration compiles to Claude's permissions block
// AND Codex's Starlark exec policy (.codex/rules/*.rules, parsed by
// codex_execpolicy — the only per-command enforcement Codex has; approval_policy
// and sandbox_mode are far coarser).
//
// Translation is safe here precisely because it is mechanical: allow/deny/ask
// exist in both dialects with the same meaning. Anything that would need
// judgement to translate stays in the per-runtime settings files instead.

const DECISIONS = { allow: 'allow', deny: 'deny', ask: 'ask' }

// Claude wraps each pattern in a tool name.
const CLAUDE_TOOL = { bash: 'Bash', edit: 'Edit', read: 'Read', write: 'Write', webfetch: 'WebFetch' }

// Codex exec policy speaks only about commands, so only `bash` maps.
const CODEX_DECISION = { allow: 'allow', deny: 'forbidden', ask: 'prompt' }

export function parsePermissions(raw, file, issues) {
  if (!raw?.permission) return null
  const out = {}
  for (const [kind, entries] of Object.entries(raw.permission)) {
    if (!CLAUDE_TOOL[kind]) {
      issues.push({ level: 'warn', file, message: `unknown permission kind "${kind}" (known: ${Object.keys(CLAUDE_TOOL).join(' ')})` })
      continue
    }
    out[kind] = {}
    for (const [pattern, decision] of Object.entries(entries)) {
      if (!DECISIONS[decision]) {
        issues.push({
          level: 'error',
          file,
          message: `permission.${kind}["${pattern}"]: "${decision}" is not allow, deny, or ask`,
        })
        continue
      }
      out[kind][pattern] = decision
    }
  }
  return { rules: out, file }
}

// → Claude's { allow: [...], deny: [...], ask: [...] }
export function toClaudePermissions(perms) {
  const buckets = { allow: [], deny: [], ask: [] }
  for (const [kind, entries] of Object.entries(perms.rules))
    for (const [pattern, decision] of Object.entries(entries))
      buckets[decision].push(`${CLAUDE_TOOL[kind]}(${pattern})`)
  const out = {}
  for (const [k, v] of Object.entries(buckets)) if (v.length) out[k] = v.sort()
  return out
}

const esc = (s) => s.replace(/["\\]/g, '\\$&')

// → Starlark prefix_rule() calls. Bash only; Codex exec policy is command-scoped.
export function toCodexRules(perms) {
  const bash = perms.rules.bash ?? {}
  const entries = Object.entries(bash)
  if (!entries.length) return null
  const lines = [
    '# Generated by meta-harness from your permissions. Edit the source, not this file.',
    '# https://developers.openai.com/codex/rules',
    '',
  ]
  for (const [pattern, decision] of entries) {
    const tokens = pattern.trim().split(/\s+/).filter(Boolean)
    lines.push(
      `# ${pattern}`,
      'prefix_rule(',
      `    pattern = [${tokens.map((t) => `"${esc(t)}"`).join(', ')}],`,
      `    decision = "${CODEX_DECISION[decision]}",`,
      ')',
      ''
    )
  }
  return lines.join('\n')
}
